---
- name: Restore PSQL on different Server
  hosts: db_servers_master
  become: yes
    vars:
     db_name: employee_db
     db_user: db_user
     #db_password: Passw0rd

  tasks:

      - name: Backup PostgreSQL
        postgresql_db:
                name: {{ db_name }}
                state: dump
                target: /home/sam/PSQL.dump.tar.gz 
---
- name: Install PSQL
  hosts: db_servers_slaves
  become: yes
  vars:
     db_name: employee_db
     db_user: db_user
     db_password: Passw0rd

  tasks:
      - name: Install PostgreSQL
        apt: name={{ item }} update_cache=true state=installed
        with_items:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python-psycopg2
        tags: packages
      
      - name: Ensure the PostgreSQL service is running
        service: name=postgresql state=started enabled=yes
      
      - name: Ensure database is created
        postgresql_db: name={{ db_name }}
                   encoding='UTF-8'
                   lc_collate='en_US.UTF-8'
                   lc_ctype='en_US.UTF-8'
                   template='template0'
                   state=present
      
      - name: Ensure user has access to the database
        postgresql_user: db={{ db_name }}
                     name={{ db_user }}
                     password=login_password: "{{ lookup('aws_secret', 'psql_db_user_password') }}"
                     priv=ALL
                     state=present
      
      - name: Ensure user does not have unnecessary privileges
        postgresql_user: name={{ db_user }}
                     role_attr_flags=NOSUPERUSER,NOCREATEDB
                     state=pr
                     
      - name: import database and restore
        postgresql_db:
        name: {{ db_name }}
        state: restore
        target: /home/sam/PSQL.dump.tar.gz
        delegate_to: '{{ groups.db_slaves[0] }}'