apiVersion: v1
kind: Service
metadata:
  labels:
    app: zalenium
    role: grid
  name: zaleniumwohelm
  namespace: zalenium-wo-helm
spec:
  type: NodePort
  ports:
  - name: hub
    nodePort: 31835
    port: 80
    protocol: TCP
    targetPort: 4444
  selector:
    app: zalenium
    role: grid