# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-logging
  namespace: kube-elk
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-elk
  name: elasticsearch-logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: elasticsearch-logging
  namespace: kube-elk
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch-logging
  apiGroup: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secrets
  namespace: kube-elk
type: Opaque
stringData:
  ELASTIC_USERNAME: "elastic"
  ELASTIC_PASSWORD: "DkIedPPSCb"  
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: kube-elk
  name: elasticsearch-config
  labels:
    app: elasticsearch
    role: master
data:
  elasticsearch.yml: |-
    cluster.name=elasticsearch-logging
    node.name=elasticsearch4
    discovery.seed_hosts=elasticsearch,elasticsearch2,elasticsearch3,elasticsearch4
    cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3,elasticsearch4  
    network.host: 0.0.0.0
    node:
      master: true
      data: false
      ingest: false
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true  
    ELASTIC_USERNAME=elastic
    ELASTIC_PASSWORD=DkIedPPSCb
---
#https://computingforgeeks.com/eks-persistent-storage-with-efs-aws-service/ 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elk-efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elk-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-bdc7b06c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-efs-claim
  namespace: kube-elk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: elk-efs-sc
  resources:
    requests:
      storage: 1Gi 
---
# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: kube-elk
  labels:
    k8s-app: elasticsearch-logging
    version: v6.2.4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: elasticsearch-logging
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v6.2.4
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v6.2.4
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
      - image: k8s.gcr.io/elasticsearch:v6.2.4
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        ##- name: elasticsearch-logging
         ## mountPath: /data
        - name: elasticsearch-config
          mountPath: /etc/elasticsearch/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        - name: elk-persistent-storage
          mountPath: /data        
      volumes:
      - name: elasticsearch-logging
        emptyDir: {}
      - name: elasticsearch-config
        configMap:
          name: elasticsearch-config
      - name: elk-persistent-storage
        persistentVolumeClaim:
          claimName: elk-efs-claim    
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-elk
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    nodePort: 31335
  selector:
    k8s-app: elasticsearch-logging
