---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: grafana-volume
spec:
   capacity:
     storage: 3Gi
     accessModes:
           - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
spec:
  accessModes:
      - ReadWriteOnce
  resources:
    requests:
       storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    purpose: example
  name: grafana-deployement
spec:
   replicas: 3
   selector:
     matchLabels:
      app: grafana
      purpose: example  
   template:
     metadata:
      labels:
        app: grafana
        purpose: example        
     spec:
      containers:
        image: grafana/grafana:latest
         name: grafana-image
         ports:
          - containerPort: 3000
            name: http-access
         volumeMounts:
           - name: grafana-volume
             mountpath: /var/lib/grafana
      volumes:
        name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui-service
  labels:
    app: grafana
    purpose: example
spec:
  type: NodePort
  ports:
    name: grafana-ui
    port: 3000
    nodePort: 30080
    protocol: TCP
    targetPort: http
  selector:
    app: grafana
    purpose: example
###https://www.metricfire.com/blog/deploying-grafana-to-kubernetes/