---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume-claim
spec:
  accessModes:
      - ReadWriteOnce
  resources:
requests:
storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana-deployement
spec:
   replicas: 3
   selector:
     matchLabels:
      app: grafana
   template:
     metadata:
      labels:
        app: grafana
     spec:
      containers:
       - image: grafana/grafana:latest
         name: grafana-image
         ports:
          - containerPort: 3000
            name: http-access
         volumeMounts: 
           - name: grafana-volume
             mountpath: /var/lib/grafana
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30080
    protocol: TCP
    targetPort: http
  selector:
    app: grafana             