apiVersion: v1
kind: Service
metadata:
  name: es-proxy
  namespace: kube-elk
  labels:
    app: es-proxy
spec:
  ports:
    - port: 9200
      name: http-es-proxy
  selector:
    app: es-proxy
  clusterIP: None