---
- name: DB_Restore_Play
  hosts: all
  become: yes
  vars:
     run_group: sam
     run_user: sam
     files:
        - sam_sundar_slave2_hq_conf_audit.sql.gz
        - sam_sundar_slave1_hq_conf_audit.sql.gz
        

  tasks:
   - name: "delete DBs on Master"
     shell: rm -f /home/sam/DB_Backups/*
     delegate_to: localhost

   - name: "delete Existing Files"
     file:
        path: /tmp/{{ item }}
        state: absent
     with_items: '{{ files }}'

   - name: "Run DB Generate Query"
     shell: /usr/bin/pg_dump HQ -t eam_platform -t eam_server -t eam_service -t eam_alert_condition -t eam_alert_definition -t eam_measurement | gzip > /tmp/$(hostname)_hq_conf_audit.sql.gz

   - name: "Fetch DB Files"
     fetch:
        src: "/tmp/{{ item }}"
        dest: "/home/sam/DB_Backups/"
        owner: "{{ run_user }}"
        group: "{{ run_group }}"
        mode: 0777
        flat: true
        ignore_errors: yes
        #remote_src: yes
     with_items: '{{ files }}'

   - name: "Changing Perm"
     shell: chmod -R 777 /home/sam/DB_Backups/
     when: inventory_hostname == 'sam_sundar_master'
