name: CI/CD

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
   deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_Root }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_Root }}
          aws-region: ap-south-1

      - name: Trigger deploy
        uses: budding-devops-blah/devops-practice@staging
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f kibana_deploy.yaml
